### ISSUE TITLE
Different memory controller configuration in full system with ruby or classic cache

### ISSUE THREAD

**Issue by jyhuang91** [darchr/gem5-skylake-config#7]
I looked into `gem5-configs/system/ruby_system.py` and `gem5-configs/system/fs.py` and found the memory controller creation is a little bit different.

In the ruby system, there is no separate kernel memory controller (4) but the classic cache system has that (8 + 1 mem_ctrls).
I also observed the interleaving schemes are different, is there any good reason to have separate configurations?

Thanks

**Comment by powerjg** [comment]
Short answer: Because Ruby can't deal with multiple address ranges easily.

The current configs are more focused on being easy to understand than being completely flexible.
